### ISSUE TITLE
01 - 04 - Blackjack

### ISSUE THREAD

**Issue by Breadkenty** [Breadkenty/assignments#4]
In this project, you are creating a playable game of
[Blackjack](https://en.wikipedia.org/wiki/Blackjack). If you haven't played this
game ever, or in a while, grab a deck of cards and play a few games.

## Objectives

- Practice the skills and ideas you have learned so far.
- Effectively use loops, conditionals, and other control structures to implement
  [control flows](https://en.wikipedia.org/wiki/Control_flow)
- Demonstrate usage of data structures to model resources.

## Requirements

Create a single-player blackjack game that plays against the house, i.e., a
human player and computer dealer. You are free to create the user interface
however you want, **but keep it simple for Explorer Mode**.

### Explorer Mode

General Rules:

- [x] The game should be played with a standard deck of playing cards (52).
- [x] The house should be dealt two cards, hidden from the player until the
      house reveals its hand.
- [x] The player should be dealt two cards, visible to the player.
- [x] The player should have a chance to hit (i.e. be dealt another card) until
      they decide to stop or they _bust_ (i.e. their total is over 21). At which
      point they lose regardless of the dealer's hand.
- [x] When the player stands, the house reveals its hand and hits (i.e. draw
      cards) until they have 17 or more.
- [x] If dealer goes over 21 the dealer loses.

- [x] The player should have two choices: "Hit" and "Stand."
- [x] Consider Aces to be worth 11, never 1.
- [x] The app should display the winner. For this mode, the winner is who is
      closer to a blackjack (21) without going over.
- [x] There should be an option to play again; this should reset the hands and
      reshuffle the deck.

### Adventure Mode

- [x] Reveal one of the house's cards to the player when cards dealt.
- [x] Consider aces be worth one _or_ eleven.
- [x] Allow the player to
      ["Split"](https://blog.betway.com/casino/blackjack-strategy-101-how-do-you-split-in-blackjack/).
- [x] Improve the win requirements. From Wikipedia:
  > Players win by not busting and having a total higher than the dealer, or not
  > busting and having the dealer bust, or getting a blackjack without the
  > dealer getting a blackjack. If the player and dealer have the same total
  > (not counting blackjacks), this is called a "push," and the player typically
  > does not win or lose money on that hand. Otherwise, the dealer wins.

### Epic Mode

- [x] Add a betting system that carries between rounds.
- [x] Allow the player to "Double down" or "Surrender."
- [x] Add more players.

**Comment by Breadkenty** [comment]
https://github.com/Breadkenty/04-Blackjack

**Comment by Breadkenty** [comment]
Code was organized until I started messing with the Console.WriteLine stuff x_x

**Comment by gstark** [comment]
This shouldn't return a generic `object` - https://github.com/Breadkenty/04-Blackjack/blob/master/Cards.cs#L49 -- it should return `string` since that is what it is. Same for the rest of `getDeck_____` methods

For this code: https://github.com/Breadkenty/04-Blackjack/blob/master/Program.cs#L32-L39 -- I hope the blackjack review showed how we can have the individual classes manage their own data. Notice how you have to keep saying `Cards.deck[0]` -- this is an indication, a "code smell", that your abstractions can be improved. Compare this code to the code we reviewed in class.

You have a `PressAnyKeyPrompt` method but then also implement
```
                Console.Write("\nPress \'H\' to hit, \'S\' to Stand: ");
                var input = Console.ReadKey();
```

Why not use your `PressAnyKeyPrompt` and have it return the pressed key? That would be good code reuse.

This code is great. However, my interpretation of reading it suggests that you are coding in a style where you are writing the major functions of your code like an outline and then filling in the code to support that outline.

I would, instead, ask you to flow through the code similar to how I did in the blackjack review. Make notes during PEDA of what classes (and their corresponding properties and behaviors) you *MAY* need. Then as you implement your algorithm, bring in those concepts.

Code written in a manner in which you write out the major functions you think you need suffers from YAGNI -- You Aint Gonna Need It. This type of code ends up being divided into methods but rigid in its ability to change. This happens because the design is based on what you _thought_ you might need, not what you actually needed when flowing through the algorithm.

**Comment by Breadkenty** [comment]
Your homework **01 - 04 - Blackjack** was marked: **Meets Expectations**

![Yas](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb161dfb00865249fe33bc4a730793f1eef22b19/neil.gif)
> &ldquo;Yas&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/3)**__

**Comment by Breadkenty** [comment]
Gavin, please give me feedback on my new blackjack game. Thank you.
https://github.com/Breadkenty/04-Blackjack

**Comment by Breadkenty** [comment]
Your homework **01 - 04 - Blackjack** was marked: **Exceeds Expectations**


![Woooooh!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--51a35f0aa3861c6c972e89ad3572a7cc7ad26dba/exceeds-1.gif)
> &ldquo;Woooooh!&rdquo;

**Comment by gstark** [comment]
Nicely done, here is some additional feedback:

Look into using a `default constructor` to make a new deck any time `new Deck` is called for: https://github.com/Breadkenty/04-Blackjack/blob/master/Deck.cs#L13

[Nice and interesting solution](https://github.com/Breadkenty/04-Blackjack/blob/master/Hand.cs#L36)

This likely creates a weird "recursion" in the program. That is the previous game is still running, just suspended while `program.RestartApplication()` is going. Later on you will discover some different patterns to address this. One thing you could do is have `Bet` return a boolean value to indicate if the user made a good bet. Or refactor `Bet` into a method that just returns the amount of the bet and then deal with the "not enough money" outside of the method so that you can more properly end a game.

Given [this](https://github.com/Breadkenty/04-Blackjack/blob/master/Player.cs#L92-L108) how do I make separate bets/plays/hits/stands against my second hand of cards? since `splitHand` only exists inside this method, how can I later add cards to it independently?
