### ISSUE TITLE
02-03 Jurassic Park - 

### ISSUE THREAD

**Issue by Breadkenty** [Breadkenty/assignments#6]
In this assignment, you will be creating a console application that manages a zoo
full of dinosaurs.

## Objectives

- Practice control structures.
- Practice data structures.
- Practice working with user data.
- Practice with LINQ.
- Practice with OOP concepts.

## Requirements

- Create a console application that manages the dinosaurs in your zoo.

### Explorer Mode

- [x] Create a class to represent your dinosaurs. The class should have the following properties

  - [x] `Name`
  - [x] `DietType` - This will be "carnivore" or "herbivore"
  - [x] `WhenAcquired` - This will default to the current time when the
        dinosaur is created
  - [x] `Weight` - How heavy the dinosaur is in pounds.
  - [x] `EnclosureNumber` - the number of the pen the dinosaur is currently in

- [x] Add a method `Description` to your class to print out a description of the dinosaur to include all of its properties. Create an output format of your choosing.
- [x] Your dinosaurs will be stored in a `List<Dinosaur>`.
- [x] When the console application runs, it should let the user choose one of the following actions:
  - [x] `View`
    - This command will show the all the dinosaurs in the list, ordered by `WhenAcquired`
  - [x] `Add`
    - This command will let the user type in the information for a dinosaur and add it to the list
  - [x] `Remove`
    - This command will prompt the user for a dinosaur name then find and delete the dinosaur with that name.
  - [x] `Transfer`
    - This command will prompt the user for a dinosaur name and a new `EnclosureNumber` and update that dino's information.
  - [x] `Summary`
    - [x] This command will display the number of carnivores and the number of herbivores.
  - [x] `Quit`
    - [x] This will stop the program

### Adventure Mode

- [x] Add an option to view the Dinosaurs acquired after a given date (to be given by the user).
- [x] Add an option to view all the Dinosaurs in a given enclosure number.

### Epic Mode

- [x] Learn how to read and write from a file. At the start of the program load all the dinosaurs from a file. When the program ends write out all the dinosaurs to the same file.

**Comment by Breadkenty** [comment]
https://github.com/Breadkenty/02-03-Jurrassic_Park

**Comment by gstark** [comment]
Excellent work. However I am sending it back to you since the formatting of the code needs _a lot_ of work.

Please fix the formatting issues I note as well as similar ones I did *not* note.


Blank line before this line please: https://github.com/Breadkenty/02-03-Jurrassic_Park/blob/master/Program.cs#L15

Blank line before: https://github.com/Breadkenty/02-03-Jurrassic_Park/blob/master/Program.cs#L32 and https://github.com/Breadkenty/02-03-Jurrassic_Park/blob/master/Program.cs#L34 and https://github.com/Breadkenty/02-03-Jurrassic_Park/blob/master/Program.cs#L35 and https://github.com/Breadkenty/02-03-Jurrassic_Park/blob/master/Program.cs#L40

Blank line and fix indentation here: https://github.com/Breadkenty/02-03-Jurrassic_Park/blob/master/Program.cs#L55

Blank line before: https://github.com/Breadkenty/02-03-Jurrassic_Park/blob/master/Program.cs#L58

Blank line before: https://github.com/Breadkenty/02-03-Jurrassic_Park/blob/master/Program.cs#L73

I'm going to stop reporting places where blank lines are needed. I hope you see the pattern. Before each logical section of things, there should be some whitespace.

Just like you look in the viewfinder of a camera and compose and balance elements in a photo, do the same with the code. Your code could be _much_ more clean and tidy.

Nice use of ReadKey: https://github.com/Breadkenty/02-03-Jurrassic_Park/blob/master/Program.cs#L141

You are using `input.KeyChar` a lot.

So consider:

```
          var key = Console.ReadKey().KeyChar;
          bool goodInput = key == 'v' || key == 'a' || key == 'r' || key == 't' || key == 's' || input.KeyChar == 'q'|| key == 'd' || key == 'e';  
```

That is cleaner.

Even cleaner:

```
          var key = Console.ReadKey().KeyChar;
          bool goodInput = "vartsqde".Contains(key);
```

Comments should align with the code: https://github.com/Breadkenty/02-03-Jurrassic_Park/blob/master/Program.cs#L157-L159

Improve the quality of this output for the user: https://github.com/Breadkenty/02-03-Jurrassic_Park/blob/master/Program.cs#L210

**I'm fairly sure you are missing a code formatting plugin**

Please run: `code --install-extension ms-dotnettools.csharp` to ensure it is installed. And ensure you have "Format on Save" enabled in your VS Code.

**Comment by Breadkenty** [comment]
Your homework **02-03 Jurassic Park - ** was marked: **Unacceptable**

![Not quite right, try again. ](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBSQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1aa2a3ebb6e61aa94cc1cd9726dc3efa40921e8c/sad-bart.gif)
> &ldquo;Not quite right, try again. &rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/58)**__

**Comment by Breadkenty** [comment]
Thanks, Gavin. I added some new things such as the Read/Write feature on the csv file, fixed the invalid input on prompts that asks for the details for the dinosaur to add, and cleaned up indents, line spacing, and redundancies.

https://github.com/Breadkenty/02-03-Jurrassic_Park

**Comment by gstark** [comment]
Very nice. I would still say one blank line before each of the `if` statements: https://github.com/Breadkenty/02-03-Jurrassic_Park/blob/master/Program.cs#L143

**Comment by Breadkenty** [comment]
Your homework **02-03 Jurassic Park - ** was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBUZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--395b5be9a8246c8cf018274388a5d5392825ae8e/giphy-2.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/67)**__
